services:
    postgresdb:
        image: postgres:16.4
        container_name: app-postgres-db
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    gcp-storage:
        image: fsouza/fake-gcs-server:1.52.2
        container_name: app-gcp-storage
        restart: no
        command: -scheme http -public-host localhost:4443 -port 4443
        ports:
            - "4443:4443"
        expose:
            - "4443"
        networks:
            - primary
        volumes:
            - "./.volumes/gcp-storage:/data"

    aws-s3:
        image: localstack/localstack:3.8.1
        container_name: app-aws-s3
        restart: no
        environment:
            SERVICES: "s3"
            AWS_DEFAULT_REGION: "us-east-1"
            AWS_S3_BUCKET_NAME: "local-bucket"
        ports:
            - "4566:4566"
        expose:
            - "4566"
        networks:
            - primary
        volumes:
            - "./scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: app-node-api
        environment:
            - .env
            - PORT=3001
        ports:
            - "3001:3001"
        command: bash -c "npm run prisma:generate && npm run start:dev"
        networks:
            - primary
        volumes:
            - ./src:/home/node/app/src

networks:
    primary:
        driver: bridge
