const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

const ACCESS_TOKEN_TTL_MINUTES = 15;
const REFRESH_TOKEN_TTL_DAYS = 30;

export const AUTH_ACCESS_COOKIE_NAME = "data_room_access_token";
export const AUTH_REFRESH_COOKIE_NAME = "data_room_refresh_token";
export const AUTH_REFRESH_COOKIE_PATH = "/api/auth/refresh";

export const AUTH_ACCESS_TOKEN_TTL = `${ACCESS_TOKEN_TTL_MINUTES}m`;
export const AUTH_REFRESH_TOKEN_TTL = `${REFRESH_TOKEN_TTL_DAYS}d`;

export const AUTH_ACCESS_COOKIE_MAX_AGE_SECONDS =
    ACCESS_TOKEN_TTL_MINUTES * SECONDS_PER_MINUTE;

export const AUTH_REFRESH_COOKIE_MAX_AGE_SECONDS =
    REFRESH_TOKEN_TTL_DAYS *
    HOURS_PER_DAY *
    MINUTES_PER_HOUR *
    SECONDS_PER_MINUTE;
