const SIGNED_URL_EXPIRES_IN_MINUTES = 15;
const SECONDS_PER_MINUTE = 60;

export const SIGNED_URL_EXPIRES_IN_SECONDS =
    SIGNED_URL_EXPIRES_IN_MINUTES * SECONDS_PER_MINUTE;

export const AWS_S3_BUCKET_NOT_CONFIGURED =
    "AWS_S3_BUCKET_NAME is not configured.";
